name: Build and Test Spring Boot with Gradle

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Instala docker-compose si es necesario.
      - name: Install Docker Compose if needed.
        run: |
          sudo apt-get update && sudo apt-get install docker.io docker-compose -y

      # Configura permisos para gradlew si es necesario.
      - name: Setup Gradle permissions if needed.
        run :
          chmod +x ./gradlew || echo "Gradle wrapper already executable."

      # Inicia servicios con Docker Compose (si los necesitas).
      - name : Start services with compose-up (if needed)
        run : |
          echo "Starting services..."
          sudo service docker start || true 
          cd .
          sudo COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 COMPOSE_HTTP_TIMEOUT=200 docker-compose up --build &> /dev/null & 

      # Ejecuta tus pruebas o tareas con Gradle.
      - name : Build and Test with Gradle
        env :
          GRADLE_USER_HOME : ~/.gradle/
        
        run : |
          ./gradlew build test --stacktrace --info --parallel --max-workers=4 || {
              echo "Error al ejecutar las pruebas o construir."
              exit 1;
          }
