name: Build and Test
on:
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java environment
        uses: actions/setup-java@v3
        
      - name: Build with Gradle # Compila con Gradle.
        run: ./gradlew build --stacktrace --info
        
      - name: Run tests with Gradle # Ejecuta pruebas unitarias con Gradle.
        run: ./gradlew test --stacktrace --info 
