name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main # Cambiar según sea necesario

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 21 for Gradle project
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # Otra distribución compatible
        
      - name: Give execution permissions to gradlew
        run: chmod +x ./gradlew
        
      - name: Build with Gradle wrapper validated by checksum verification if needed or simply run the wrapper directly if trusted source!
        run: ./gradlew clean bootJar --no-daemon --stacktrace --info --parallel
        
